<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: google/cloud/dialogflow/cx/v3/agent.proto

namespace Google\Cloud\Dialogflow\Cx\V3;

if (false) {
    /**
     * This class is deprecated. Use Google\Cloud\Dialogflow\Cx\V3\ExportAgentRequest\DataFormat instead.
     * @deprecated
     */
    class ExportAgentRequest_DataFormat {}
}
class_exists(ExportAgentRequest\DataFormat::class);
@trigger_error('Google\Cloud\Dialogflow\Cx\V3\ExportAgentRequest_DataFormat is deprecated and will be removed in the next major release. Use Google\Cloud\Dialogflow\Cx\V3\ExportAgentRequest\DataFormat instead', E_USER_DEPRECATED);

